default:
	  javac cpsc2150/connectX/AbsGameBoard.java cpsc2150/connectX/BoardPosition.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/GameScreen.java cpsc2150/connectX/IGameBoard.java

run:
	  java cpsc2150/connectX/GameScreen

test:
	  javac -cp .:/usr/share/java/junit4.jar cpsc2150/connectX/*.java

testGB:
	  java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.connectX.TestGameBoard

testGBMem:
	  java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.connectX.TestGameBoardMem

clean:
	  rm -f cpsc2150/connectX/*.class

